### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by WindowsNT** [rfn123/equirectangular-to-rectlinear#2]
std::pair<double, double> Equi2Rect::reprojection(int x_img, int y_img)
{

    cv::Mat xyz, xyz_norm;
    cv::Mat ray3d, RK;
    double xp, yp, zp, theta, phi;
    double x_sphere, y_sphere;

    xyz = (cv::Mat_<double>(3, 1) << (double)x_img, (double)y_img, 1);
    xyz_norm = xyz / norm(xyz);
    RK = Rot * K.inv();
    ray3d = RK * xyz_norm;

    //get 3d spherical coordinates
    xp = ray3d.at<double>(0, 0);
-->    yp = ray3d.at<double>(0, 1);

You initialize a matrix of 3x1 and then try to access 0,1

**Comment by rfn123** [comment]
Hi, thanks for opening this issue!
Does the program really crash in your case? I cannot reproduce the crash on my pc. 
It seems that `cv::Mat::at` is intelligent enough to recognize that `ray3d` is a row vector instead of a column vector,
at least swapping the indices in the line `xp = ray3d.at(0,1)` to `xp =  ray3d.at(1,0)` makes no difference for me. 
But I will fix this to a less confusing way.
